name: Build Kivy APK

on:
  push:
    branches:
      - main  # Change this if your branch is different

jobs:
  build:
    runs-on: ubuntu-22.04  # ✅ Fix: Use Ubuntu 22.04 (Ubuntu 24.04 breaks libtinfo5)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"  # ✅ Ensures correct Python version for Buildozer

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"  # ✅ Java 11 recommended for Buildozer

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libncurses5 libncursesw5  # ✅ Fix for libtinfo5 issue
          sudo apt install -y python3-venv zip unzip git

      - name: Set up Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel

      - name: Install Buildozer & Dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade buildozer cython virtualenv
          sudo apt install -y autoconf automake build-essential \
              ccache git libffi-dev libltdl-dev libssl-dev \
              libtool pkg-config python3-pip python3-setuptools \
              python3-venv zip unzip

      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4  # ✅ Updated to v4
        with:
          name: Kivy-APK
          path: bin/*.apk
